version: '3.9'
services:
  db:
    container_name: career_quest
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: career_quest

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
